# Based on: https://www.linkedin.com/pulse/deploy-nextjs-app-github-pages-federico-antu%C3%B1a/

name: Deploy to GitHub Pages


on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /dbux-pdg

    strategy:
      matrix:
        node-version: [16.x]


    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn ci # see https://stackoverflow.com/questions/58482655/what-is-the-closest-to-npm-ci-in-yarn
      - name: Build project
        run: yarn build
      - name: Export static files
        run: yarn export # see https://nextjs.org/docs/advanced-features/static-html-export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out